import csv
import json
import re
import zipfile
from functools import lru_cache
from io import BytesIO, StringIO
from pathlib import Path
from threading import Lock
from typing import Annotated

from fastapi import FastAPI, File, Form, HTTPException, Response, UploadFile
from fastapi.responses import FileResponse, JSONResponse, RedirectResponse, StreamingResponse
from PIL import Image, ImageOps
from pydantic import BaseModel, Field

from memora.clustering.journey import JourneyConfig, NamedLocation, resolve_location_name
from memora.clustering.location_inference import infer_journey_config
from memora.clustering.people import (
    apply_feedback,
    cluster_people,
    load_people_index,
    save_people_index,
    set_person_name,
)
from memora.config import settings
from memora.encoders.clip_encoder import create_encoder
from memora.encoders.face_encoder import InsightFaceEncoder
from memora.generation.narrative import (
    ChatCompletionsBackend,
    NarrativeBackendUnavailable,
    generate_event_narrative,
    generate_journey_narrative,
)
from memora.indexer import IMAGE_EXTENSIONS, iter_images, photo_id
from memora.integrations.immich import ImmichClient, ImmichError, sync_immich_assets
from memora.projects import ProjectCatalog
from memora.quality.best_shot import score_photo
from memora.retrieval.metadata_filter import GeoBounds
from memora.service import MemoraService

app = FastAPI(title="Memora AI", version="0.7.0", description="Independent photo understanding service")
service = MemoraService(create_encoder(settings.encoder, model_name=settings.clip_model, pretrained=settings.clip_pretrained), settings.index_path)
immich_sync_lock = Lock()
project_analysis_lock = Lock()
projects = ProjectCatalog(settings.projects_path)
PROJECT_EVENT_STRATEGY = "strict_event_people"


@app.get("/", include_in_schema=False)
def root() -> RedirectResponse:
    """Send browser visits to the interactive API documentation."""
    return RedirectResponse(url="/docs", status_code=307)


class IndexRequest(BaseModel):
    directory: str
    index_path: str | None = None


class SearchRequest(BaseModel):
    query: str = Field(min_length=1)
    top_k: int = Field(default=20, ge=1, le=200)
    min_score: float | None = None
    strategy: str = Field(default="query_enhancement", pattern="^(raw_clip|prompt_ensemble|query_enhancement)$")
    captured_from: str | None = None
    captured_to: str | None = None
    bbox: list[float] | None = Field(default=None, min_length=4, max_length=4)
    fallback_if_unavailable: bool = False
    reference_date: str | None = None


class PeopleClusterRequest(BaseModel):
    people_path: str = "data/people.json"
    model_name: str = "buffalo_l"
    ctx_id: int | None = Field(default=None, ge=-1, le=0)
    eps: float = Field(default=0.35, gt=0)
    min_samples: int = Field(default=2, ge=2)


class PeopleMergeRequest(BaseModel):
    people_path: str = "data/people.json"
    person_ids: list[int] = Field(min_length=2)


class PeopleRemovePhotoRequest(BaseModel):
    people_path: str = "data/people.json"
    person_id: int
    photo_id: str = Field(min_length=1)


class PeopleNameRequest(BaseModel):
    people_path: str = "data/people.json"
    person_id: int
    name: str = Field(min_length=1)


class ProjectAnnotationRequest(BaseModel):
    name: str | None = Field(default=None, max_length=200)
    note: str | None = Field(default=None, max_length=4000)
    auto_generate_name: bool = False
    auto_generate_note: bool = False


class ProjectGenerateRequest(BaseModel):
    field: str = Field(pattern="^(name|note)$")


class NamedLocationRequest(BaseModel):
    name: str = Field(min_length=1)
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    radius_km: float = Field(default=80.0, gt=0)


class JourneyDiscoverRequest(BaseModel):
    home: NamedLocationRequest | None = None
    destinations: list[NamedLocationRequest] = Field(default_factory=list)
    max_gap_days: float = Field(default=5.0, gt=0)
    stop_radius_km: float = Field(default=150.0, gt=0)
    location_cluster_radius_km: float = Field(default=40.0, gt=0)
    minimum_destination_photos: int = Field(default=2, ge=1)
    people_path: str = "data/people.json"
    strategy: str = Field(default="strict_event_people", pattern="^(strict_event|strict_event_people)$")
    use_llm: bool | None = None


class ImmichSyncRequest(BaseModel):
    page_size: int = Field(default=250, ge=1, le=1000)
    force: bool = False
    prune_missing: bool = False


class ImmichAlbumRequest(BaseModel):
    album_name: str = Field(min_length=1, max_length=200)
    photo_ids: list[str] = Field(min_length=1)
    description: str = Field(default="Generated by Memora AI", max_length=2000)


class ProjectCreateRequest(BaseModel):
    name: str = Field(min_length=1, max_length=120)


class ProjectAnalyzeRequest(BaseModel):
    encoder: str | None = Field(default=None, pattern="^(lightweight|open_clip)$")


@lru_cache(maxsize=2)
def _project_encoder(kind: str):
    if kind == settings.encoder:
        return service.encoder
    return create_encoder(
        kind,
        model_name=settings.clip_model,
        pretrained=settings.clip_pretrained,
    )


def _face_ctx_id(requested: int | None) -> int:
    if requested is not None:
        return requested
    try:
        import onnxruntime  # type: ignore

        return 0 if "CUDAExecutionProvider" in onnxruntime.get_available_providers() else -1
    except ImportError:
        return -1


def _enrich_quality_with_faces(project_service: MemoraService, people_index) -> None:
    faces_by_photo: dict[str, list[dict[str, object]]] = {}
    for face in people_index.faces:
        faces_by_photo.setdefault(face.photo_id, []).append(
            {"bbox": face.bbox, "det_score": face.det_score}
        )
    for record in project_service.records:
        record.quality = score_photo(record.path, faces=faces_by_photo.get(record.id, []))
    project_service.store.save(project_service.index_path)


def _immich_client() -> ImmichClient:
    if not settings.immich_url or not settings.immich_api_key:
        raise HTTPException(
            status_code=503,
            detail="Immich is not configured; set MEMORA_IMMICH_URL and MEMORA_IMMICH_API_KEY",
        )
    return ImmichClient(
        settings.immich_url,
        settings.immich_api_key,
        timeout=settings.immich_timeout_seconds,
    )


def _immich_call(callback):
    try:
        return callback()
    except (ImmichError, ValueError) as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc


def _project(project_id: str):
    try:
        return projects.get(project_id)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


def _project_service(project_id: str) -> MemoraService:
    project = _project(project_id)
    encoder_kind = project.encoder or settings.encoder
    try:
        encoder = _project_encoder(encoder_kind)
    except (ImportError, RuntimeError) as exc:
        raise HTTPException(
            status_code=503,
            detail=f"Project encoder '{encoder_kind}' is unavailable: {exc}",
        ) from exc
    project_service = MemoraService(encoder, projects.index_path(project_id))
    if (
        project_service.records
        and project.embedding_dimension
        and project.embedding_dimension != encoder.dimension
    ):
        raise HTTPException(
            status_code=409,
            detail="The project index was created with a different encoder. Re-analyze the project.",
        )
    return project_service


def _project_photo(project_id: str, requested_id: str) -> Path:
    project_service = _project_service(project_id)
    candidates = {
        record.id: Path(record.path)
        for record in project_service.records
    }
    if requested_id not in candidates:
        candidates.update({photo_id(path): path for path in iter_images(projects.uploads(project_id))})
    path = candidates.get(requested_id)
    upload_root = projects.uploads(project_id).resolve()
    if path is None or upload_root not in path.resolve().parents or not path.is_file():
        raise HTTPException(status_code=404, detail="Photo not found")
    return path


def _person_cover_data(project_id: str, person_id: int):
    index = load_people_index(projects.people_path(project_id))
    group = next((value for value in index.groups if value.id == person_id), None)
    if group is None:
        raise HTTPException(status_code=404, detail="Person not found")
    records = {record.id: record for record in _project_service(project_id).records}
    faces = [face for face in index.faces if face.id in group.face_ids]
    all_face_counts: dict[str, int] = {}
    for face in index.faces:
        all_face_counts[face.photo_id] = all_face_counts.get(face.photo_id, 0) + 1
    single_photos = [photo for photo in group.photo_ids if all_face_counts.get(photo) == 1]
    candidates = single_photos or group.photo_ids
    cover_id = max(
        candidates,
        key=lambda photo: records.get(photo).quality.get("score", 0.0) if records.get(photo) else 0.0,
        default=None,
    )
    if cover_id is None:
        raise HTTPException(status_code=404, detail="Person has no photos")
    face = max(
        (value for value in faces if value.photo_id == cover_id),
        key=lambda value: value.det_score,
        default=None,
    )
    return cover_id, face, not bool(single_photos)


def _llm_backend(enabled: bool | None):
    if enabled is False:
        return None
    if not settings.llm_url or not settings.llm_model:
        return None
    return ChatCompletionsBackend(settings.llm_url, settings.llm_model, settings.llm_api_key)


def _llm_status(backend: ChatCompletionsBackend | None) -> dict:
    return {
        "configured": bool(settings.llm_url and settings.llm_model),
        "available": backend.available if backend else False,
        "fallback_reason": backend.last_error if backend else None,
    }


@app.get("/health")
def health() -> dict:
    return {
        "status": "ok",
        "photos": len(service.records),
        "encoder": service.encoder.__class__.__name__,
        "immich_configured": bool(settings.immich_url and settings.immich_api_key),
        "llm_configured": bool(settings.llm_url and settings.llm_model),
    }


@app.post("/index")
def index(request: IndexRequest) -> dict:
    directory = Path(request.directory)
    if not directory.is_dir():
        raise HTTPException(status_code=400, detail=f"Directory does not exist: {directory}")
    if request.index_path:
        service.index_path = Path(request.index_path)
    records = service.index(directory)
    return {"count": len(records), "index_path": str(service.index_path)}


@app.get("/projects")
def list_projects() -> dict:
    return {"projects": [project.to_dict() for project in projects.list()]}


@app.post("/projects")
def create_project(request: ProjectCreateRequest) -> dict:
    try:
        return projects.create(request.name).to_dict()
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.post("/projects/{project_id}/files")
async def upload_project_files(
    project_id: str,
    files: Annotated[list[UploadFile], File()],
    relative_paths: Annotated[list[str] | None, Form()] = None,
) -> dict:
    project = _project(project_id)
    if relative_paths and len(relative_paths) != len(files):
        raise HTTPException(status_code=400, detail="relative_paths must match the uploaded files")
    uploaded = 0
    rejected: list[str] = []
    for index, upload in enumerate(files):
        source_name = relative_paths[index] if relative_paths else (upload.filename or "")
        suffix = Path(source_name).suffix.lower()
        if suffix not in IMAGE_EXTENSIONS:
            rejected.append(source_name)
            continue
        try:
            destination = projects.safe_upload_path(project_id, source_name)
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        destination.parent.mkdir(parents=True, exist_ok=True)
        size = 0
        with destination.open("wb") as output:
            while chunk := await upload.read(1024 * 1024):
                size += len(chunk)
                if size > 100 * 1024 * 1024:
                    output.close()
                    destination.unlink(missing_ok=True)
                    raise HTTPException(status_code=413, detail=f"File exceeds 100 MB: {source_name}")
                output.write(chunk)
        uploaded += 1
    total = len(iter_images(projects.uploads(project_id)))
    project = projects.touch(project.id, photo_count=total, status="uploaded")
    return {"project": project.to_dict(), "uploaded": uploaded, "rejected": rejected}


@app.post("/projects/{project_id}/analyze")
def analyze_project(project_id: str, request: ProjectAnalyzeRequest | None = None) -> dict:
    project = _project(project_id)
    if not project.photo_count:
        raise HTTPException(status_code=400, detail="Upload photos before starting analysis")
    with project_analysis_lock:
        projects.touch(project_id, status="analyzing")
        try:
            encoder_kind = request.encoder if request and request.encoder else settings.encoder
            encoder = _project_encoder(encoder_kind)
            project_service = MemoraService(encoder, projects.index_path(project_id))
            records = project_service.index(projects.uploads(project_id))
            people_index = load_people_index(projects.people_path(project_id))
            if people_index.faces:
                _enrich_quality_with_faces(project_service, people_index)
            project = projects.touch(
                project_id,
                photo_count=len(records),
                analyzed_count=len(records),
                status="ready",
                encoder=encoder_kind,
                embedding_dimension=encoder.dimension,
            )
        except (ImportError, OSError, RuntimeError, ValueError) as exc:
            projects.touch(project_id, status="uploaded")
            raise HTTPException(status_code=400, detail=str(exc)) from exc
    return {"project": project.to_dict(), "index_path": str(projects.index_path(project_id))}


@app.get("/projects/{project_id}/photos")
def project_photos(project_id: str) -> dict:
    project_service = _project_service(project_id)
    if project_service.records:
        values = [
            {
                "id": record.id,
                "filename": record.original_filename or Path(record.path).name,
                "relative_path": Path(record.path).resolve().relative_to(projects.uploads(project_id).resolve()).as_posix(),
                "captured_at": record.captured_at,
                "width": record.width,
                "height": record.height,
                "quality_score": record.quality.get("score"),
                "url": f"/projects/{project_id}/photos/{record.id}/content",
            }
            for record in project_service.records
        ]
    else:
        values = [
            {
                "id": photo_id(path),
                "filename": path.name,
                "relative_path": path.resolve().relative_to(projects.uploads(project_id).resolve()).as_posix(),
                "captured_at": None,
                "width": 0,
                "height": 0,
                "quality_score": None,
                "url": f"/projects/{project_id}/photos/{photo_id(path)}/content",
            }
            for path in iter_images(projects.uploads(project_id))
        ]
    return {"photos": values}


@app.get("/projects/{project_id}/photos/{requested_id}/content")
def project_photo_content(project_id: str, requested_id: str) -> FileResponse:
    return FileResponse(_project_photo(project_id, requested_id))


@app.post("/projects/{project_id}/search")
def project_search(project_id: str, request: SearchRequest) -> dict:
    project_service = _project_service(project_id)
    return project_service.search_details(
        request.query,
        request.top_k,
        request.min_score,
        request.strategy,
        captured_from=request.captured_from,
        captured_to=request.captured_to,
        bounds=GeoBounds(*request.bbox) if request.bbox else None,
        fallback_if_unavailable=request.fallback_if_unavailable,
        reference_date=request.reference_date,
    )


@app.get("/projects/{project_id}/events")
def project_events(project_id: str, strategy: str = PROJECT_EVENT_STRATEGY) -> dict:
    if strategy not in {"time_only", "time_clip", "time_clip_gps", "strict_event", "strict_event_people"}:
        raise HTTPException(status_code=400, detail="Unsupported project event strategy")
    project_service = _project_service(project_id)
    people_index = load_people_index(projects.people_path(project_id))
    values = project_service.events(strategy=strategy, people_index=people_index)
    annotations = projects.load_annotations(project_id)["events"]
    payload = []
    for event in values:
        item = {**event.__dict__, **annotations.get(str(event.id), {})}
        payload.append(item)
    return {"strategy": strategy, "events": payload}


@app.get("/projects/{project_id}/journeys")
def project_journeys(project_id: str) -> dict:
    project_service = _project_service(project_id)
    try:
        config, _ = infer_journey_config(project_service.records, geocode=True)
        events, journeys = project_service.journeys(
            config,
            people_path=projects.people_path(project_id),
            strategy=PROJECT_EVENT_STRATEGY,
            generate_narratives=False,
        )
    except ValueError:
        events = []
        journeys = []
    events_by_id = {event.id: event for event in events}
    annotations = projects.load_annotations(project_id)["journeys"]
    payload = []
    for journey in journeys:
        item = {**journey.__dict__, "photo_ids": [photo_id for event_id in journey.event_ids for photo_id in (events_by_id[event_id].photo_ids if event_id in events_by_id else [])]}
        item.update(annotations.get(str(journey.id), {}))
        payload.append(item)
    return {"event_strategy": PROJECT_EVENT_STRATEGY, "journeys": payload}


@app.get("/projects/{project_id}/annotations")
def project_annotations(project_id: str) -> dict:
    _project(project_id)
    return projects.load_annotations(project_id)


@app.put("/projects/{project_id}/annotations/{kind}/{item_id}")
def update_project_annotation(project_id: str, kind: str, item_id: int, request: ProjectAnnotationRequest) -> dict:
    _project(project_id)
    if kind not in {"people", "events", "journeys"}:
        raise HTTPException(status_code=400, detail="Unsupported annotation kind")
    annotations = projects.load_annotations(project_id)
    current = annotations[kind].get(str(item_id), {})
    name = request.name.strip() if request.name else current.get("name")
    note = request.note.strip() if request.note else current.get("note")
    if request.auto_generate_name and not name:
        name = f"{kind[:-1].title()} {item_id + 1}"
    if request.auto_generate_note and not note:
        note = f"{name or kind.title()} — generated by Memora AI"
    annotations[kind][str(item_id)] = {"name": name, "note": note, "name_source": "llm" if request.auto_generate_name else current.get("name_source", "human")}
    projects.save_annotations(project_id, annotations)
    return {"annotation": annotations[kind][str(item_id)]}


@app.post("/projects/{project_id}/annotations/{kind}/{item_id}/generate")
def generate_project_annotation(project_id: str, kind: str, item_id: int, request: ProjectGenerateRequest) -> dict:
    _project(project_id)
    if kind not in {"people", "events", "journeys"}:
        raise HTTPException(status_code=400, detail="Unsupported annotation kind")
    backend = _llm_backend(True)
    if backend is None:
        raise HTTPException(
            status_code=503,
            detail="LLM is not configured. Set MEMORA_LLM_URL, MEMORA_LLM_MODEL and, for cloud providers, MEMORA_LLM_API_KEY.",
        )
    project_service = _project_service(project_id)
    people_index = load_people_index(projects.people_path(project_id))
    try:
        if kind == "people":
            person = next((value for value in people_index.groups if value.id == item_id), None)
            if person is None:
                raise HTTPException(status_code=404, detail="Person not found")
            records = {record.id: record for record in project_service.records}
            dates = sorted(
                record.captured_at
                for photo_id in person.photo_ids
                if (record := records.get(photo_id)) is not None and record.captured_at
            )
            generated = backend.generate_json(
                "person_profile",
                {
                    "person_id": person.id,
                    "current_name": person.name,
                    "photo_count": len(person.photo_ids),
                    "first_seen": dates[0] if dates else None,
                    "last_seen": dates[-1] if dates else None,
                    "instruction": "Do not invent a real identity. Use a neutral descriptive label when no human name is known.",
                },
            )
            value = generated[request.field]
        elif kind == "events":
            event = next(
                (value for value in project_service.events(strategy=PROJECT_EVENT_STRATEGY, people_index=people_index) if value.id == item_id),
                None,
            )
            if event is None:
                raise HTTPException(status_code=404, detail="Event not found")
            try:
                event_config, _ = infer_journey_config(project_service.records, geocode=True)
                place_name = resolve_location_name(event, (event_config.home,) + event_config.destinations)
            except ValueError:
                place_name = None
            generated_event = generate_event_narrative(
                event,
                {record.id: record for record in project_service.records},
                people_index,
                project_service.encoder,
                backend,
                place_name=place_name,
            )
            if generated_event.name_source != "llm":
                raise NarrativeBackendUnavailable(backend.last_error or "LLM did not return a valid event response")
            value = generated_event.name if request.field == "name" else generated_event.summary
        else:
            config, _ = infer_journey_config(project_service.records, geocode=True)
            events, journeys = project_service.journeys(
                config,
                people_index=people_index,
                backend=None,
                generate_narratives=False,
            )
            journey = next((value for value in journeys if value.id == item_id), None)
            if journey is None:
                raise HTTPException(status_code=404, detail="Journey not found")
            generated_journey = generate_journey_narrative(
                journey,
                {event.id: event for event in events},
                people_index,
                backend,
            )
            if generated_journey.name_source != "llm":
                raise NarrativeBackendUnavailable(backend.last_error or "LLM did not return a valid journey response")
            value = generated_journey.name if request.field == "name" else generated_journey.note
    except NarrativeBackendUnavailable as exc:
        raise HTTPException(status_code=502, detail=f"LLM request failed: {exc}") from exc
    if not value:
        raise HTTPException(status_code=502, detail="LLM returned an empty value")
    return {"field": request.field, "value": str(value), "source": "llm"}


@app.get("/projects/{project_id}/similar-groups")
def project_similar_groups(project_id: str) -> dict:
    values = _project_service(project_id).similar_groups()
    return {"groups": [value.__dict__ for value in values]}


@app.get("/projects/{project_id}/people")
def project_people(project_id: str) -> dict:
    _project(project_id)
    index = load_people_index(projects.people_path(project_id))
    records = {record.id: record for record in _project_service(project_id).records}
    face_counts: dict[str, int] = {}
    for face in index.faces:
        face_counts[face.photo_id] = face_counts.get(face.photo_id, 0) + 1
    annotations = projects.load_annotations(project_id)["people"]
    groups = []
    for group in index.groups:
        candidates = [photo for photo in group.photo_ids if face_counts.get(photo) == 1] or group.photo_ids
        cover = max(candidates, key=lambda photo: records.get(photo).quality.get("score", 0.0) if records.get(photo) else 0.0, default=None)
        item = {**group.__dict__, "cover_photo_id": cover, "cover_url": f"/projects/{project_id}/people/{group.id}/cover", **annotations.get(str(group.id), {})}
        groups.append(item)
    return {"groups": groups, "faces": [face.__dict__ for face in index.faces]}


@app.get("/projects/{project_id}/people/{person_id}/cover")
def project_person_cover(project_id: str, person_id: int):
    cover_id, face, crop_face = _person_cover_data(project_id, person_id)
    path = _project_photo(project_id, cover_id)
    if not crop_face or face is None or len(face.bbox) < 4:
        return FileResponse(path)
    with Image.open(path) as source:
        image = ImageOps.exif_transpose(source).convert("RGB")
        left, top, right, bottom = (float(value) for value in face.bbox[:4])
        face_width, face_height = max(1.0, right - left), max(1.0, bottom - top)
        side = max(face_width, face_height) * 2.2
        center_x, center_y = (left + right) / 2, (top + bottom) / 2
        crop = (
            max(0, int(center_x - side / 2)),
            max(0, int(center_y - side / 2)),
            min(image.width, int(center_x + side / 2)),
            min(image.height, int(center_y + side / 2)),
        )
        portrait = image.crop(crop)
        output = BytesIO()
        portrait.save(output, format="JPEG", quality=90, optimize=True)
        output.seek(0)
    return StreamingResponse(output, media_type="image/jpeg", headers={"Cache-Control": "private, max-age=3600"})


@app.post("/projects/{project_id}/people/cluster")
def cluster_project_people(project_id: str, request: PeopleClusterRequest) -> dict:
    project_service = _project_service(project_id)
    if not project_service.records:
        raise HTTPException(status_code=400, detail="Analyze the project before clustering people")
    try:
        ctx_id = _face_ctx_id(request.ctx_id)
        encoder = InsightFaceEncoder(model_name=request.model_name, ctx_id=ctx_id)
        people_index = cluster_people(
            project_service.records,
            encoder,
            model_name=request.model_name,
            eps=request.eps,
            min_samples=request.min_samples,
        )
        save_people_index(people_index, projects.people_path(project_id))
        _enrich_quality_with_faces(project_service, people_index)
    except (ImportError, RuntimeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    records = {record.id: record for record in project_service.records}
    annotations = projects.load_annotations(project_id)["people"]
    face_counts: dict[str, int] = {}
    for face in people_index.faces:
        face_counts[face.photo_id] = face_counts.get(face.photo_id, 0) + 1
    groups = []
    for group in people_index.groups:
        candidates = [photo for photo in group.photo_ids if face_counts.get(photo) == 1] or group.photo_ids
        cover = max(candidates, key=lambda photo: records.get(photo).quality.get("score", 0.0) if records.get(photo) else 0.0, default=None)
        groups.append({
            **group.__dict__,
            "cover_photo_id": cover,
            "cover_url": f"/projects/{project_id}/people/{group.id}/cover",
            **annotations.get(str(group.id), {}),
        })
    return {"groups": groups, "faces": [face.__dict__ for face in people_index.faces], "ctx_id": ctx_id}


@app.get("/projects/{project_id}/best-shots")
def project_best_shots(project_id: str, limit: int = 30) -> dict:
    records = sorted(
        _project_service(project_id).records,
        key=lambda record: record.quality.get("score", 0.0),
        reverse=True,
    )[: max(1, min(limit, 200))]
    return {
        "photos": [
            {
                "id": record.id,
                "filename": Path(record.path).name,
                "score": record.quality.get("score", 0.0),
                "url": f"/projects/{project_id}/photos/{record.id}/content",
            }
            for record in records
        ]
    }


@app.get("/projects/{project_id}/export/manifest")
def export_project_manifest(project_id: str) -> JSONResponse:
    project = _project(project_id)
    project_service = _project_service(project_id)
    payload = {
        "format": "memora-project-v1",
        "project": project.to_dict(),
        "photos": [record.to_dict() for record in project_service.records],
        "events": [
            event.__dict__
            for event in project_service.events(
                strategy=PROJECT_EVENT_STRATEGY,
                people_path=projects.people_path(project_id),
            )
        ],
        "similar_groups": [group.__dict__ for group in project_service.similar_groups()],
    }
    filename = re.sub(r"[^A-Za-z0-9_-]+", "-", project.name).strip("-") or project.id
    return JSONResponse(
        payload,
        headers={"Content-Disposition": f'attachment; filename="{filename}-manifest.json"'},
    )


@app.get("/projects/{project_id}/export/photos.csv")
def export_project_csv(project_id: str) -> Response:
    project = _project(project_id)
    output = StringIO()
    writer = csv.writer(output)
    writer.writerow(["photo_id", "filename", "captured_at", "latitude", "longitude", "quality_score"])
    for record in _project_service(project_id).records:
        writer.writerow([
            record.id,
            Path(record.path).name,
            record.captured_at or "",
            record.latitude if record.latitude is not None else "",
            record.longitude if record.longitude is not None else "",
            record.quality.get("score", ""),
        ])
    filename = re.sub(r"[^A-Za-z0-9_-]+", "-", project.name).strip("-") or project.id
    return Response(
        content="\ufeff" + output.getvalue(),
        media_type="text/csv; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{filename}-photos.csv"'},
    )


@app.get("/projects/{project_id}/export/best-shots.zip")
def export_best_shots_zip(project_id: str, limit: int = 20) -> FileResponse:
    project = _project(project_id)
    records = sorted(
        _project_service(project_id).records,
        key=lambda record: record.quality.get("score", 0.0),
        reverse=True,
    )[: max(1, min(limit, 50))]
    if not records:
        raise HTTPException(status_code=400, detail="Analyze the project before exporting best shots")
    export_dir = projects.directory(project_id) / "exports"
    export_dir.mkdir(parents=True, exist_ok=True)
    archive = export_dir / "best-shots.zip"
    manifest = []
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as output:
        for rank, record in enumerate(records, start=1):
            source = Path(record.path)
            name = f"{rank:02d}-{record.id}-{source.name}"
            output.write(source, arcname=f"photos/{name}")
            manifest.append({
                "rank": rank,
                "photo_id": record.id,
                "filename": source.name,
                "quality": record.quality,
            })
        output.writestr(
            "best-shots.json",
            json.dumps({"project": project.to_dict(), "photos": manifest}, ensure_ascii=False, indent=2),
        )
    filename = re.sub(r"[^A-Za-z0-9_-]+", "-", project.name).strip("-") or project.id
    return FileResponse(archive, filename=f"{filename}-best-shots.zip", media_type="application/zip")


@app.post("/search")
def search(request: SearchRequest) -> dict:
    bounds = GeoBounds(*request.bbox) if request.bbox else None
    response = service.search_details(
        request.query,
        request.top_k,
        request.min_score,
        request.strategy,
        captured_from=request.captured_from,
        captured_to=request.captured_to,
        bounds=bounds,
        fallback_if_unavailable=request.fallback_if_unavailable,
        reference_date=request.reference_date,
    )
    for result in response["results"]:
        if result.get("source") == "immich":
            result["immich_asset_id"] = result["photo_id"]
            result["thumbnail_url"] = f"/immich/assets/{result['photo_id']}/thumbnail"
    return response


@app.get("/immich/status")
def immich_status() -> dict:
    client = _immich_client()
    return _immich_call(client.status)


@app.post("/immich/sync")
def immich_sync(request: ImmichSyncRequest) -> dict:
    client = _immich_client()
    with immich_sync_lock:
        return _immich_call(
            lambda: sync_immich_assets(
                client,
                service.encoder,
                service.store,
                service.index_path,
                settings.immich_cache_path,
                page_size=request.page_size,
                force=request.force,
                prune_missing=request.prune_missing,
            ).to_dict()
        )


@app.get("/immich/assets/{asset_id}/thumbnail")
def immich_thumbnail(asset_id: str, size: str = "preview") -> Response:
    if size not in {"thumbnail", "preview", "fullsize"}:
        raise HTTPException(status_code=400, detail="size must be thumbnail, preview, or fullsize")
    payload, content_type = _immich_call(lambda: _immich_client().thumbnail(asset_id, size=size))
    return Response(content=payload, media_type=content_type.split(";", 1)[0])


@app.post("/immich/albums")
def immich_album(request: ImmichAlbumRequest) -> dict:
    known_immich_ids = {record.id for record in service.records if record.source == "immich"}
    unknown = sorted(set(request.photo_ids) - known_immich_ids)
    if unknown:
        raise HTTPException(
            status_code=400,
            detail={"message": "Some photos are not synced Immich assets", "photo_ids": unknown},
        )
    client = _immich_client()
    return _immich_call(
        lambda: client.create_album(request.album_name, request.photo_ids, description=request.description)
    )


@app.get("/events")
def events(
    strategy: str = "time_clip_gps",
    people_path: str = "data/people.json",
    generate_names: bool = False,
    use_llm: bool | None = None,
) -> dict:
    valid = {"time_only", "time_clip", "time_clip_gps", "strict_event", "strict_event_people"}
    if strategy not in valid:
        raise HTTPException(status_code=400, detail=f"strategy must be one of: {', '.join(sorted(valid))}")
    if generate_names:
        try:
            inferred_config, _ = infer_journey_config(service.records)
            locations = (inferred_config.home,) + inferred_config.destinations
        except ValueError:
            locations = ()
        backend = _llm_backend(use_llm)
        values = service.named_events(
            strategy=strategy,
            people_path=people_path,
            backend=backend,
            locations=locations,
        )
    else:
        values = service.events(strategy=strategy, people_path=people_path)
    response = {"strategy": strategy, "events": [event.__dict__ for event in values]}
    if generate_names:
        response["narrative_backend"] = _llm_status(backend)
    return response


@app.post("/journeys/discover")
def journeys(request: JourneyDiscoverRequest) -> dict:
    if request.home is None:
        try:
            config, location_clusters = infer_journey_config(
                service.records,
                cluster_radius_km=request.location_cluster_radius_km,
                minimum_destination_photos=request.minimum_destination_photos,
                max_gap_days=request.max_gap_days,
                stop_radius_km=request.stop_radius_km,
            )
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        location_mode = "auto_gps"
    else:
        config = JourneyConfig(
            home=NamedLocation(
                request.home.name,
                request.home.latitude,
                request.home.longitude,
                request.home.radius_km,
            ),
            destinations=tuple(
                NamedLocation(value.name, value.latitude, value.longitude, value.radius_km)
                for value in request.destinations
            ),
            max_gap_days=request.max_gap_days,
            stop_radius_km=request.stop_radius_km,
        )
        location_clusters = []
        location_mode = "manual_override"
    backend = _llm_backend(request.use_llm)
    events, values = service.journeys(
        config,
        people_path=request.people_path,
        strategy=request.strategy,
        backend=backend,
    )
    return {
        "config": config.to_dict(),
        "location_mode": location_mode,
        "location_clusters": [cluster.to_dict() for cluster in location_clusters],
        "narrative_backend": _llm_status(backend),
        "event_count": len(events),
        "journeys": [journey.__dict__ for journey in values],
    }


@app.get("/similar-groups")
def similar_groups() -> dict:
    return {"groups": [group.__dict__ for group in service.similar_groups()]}


@app.get("/quality/{photo_id}")
def quality(photo_id: str) -> dict:
    for record in service.records:
        if record.id == photo_id:
            return {"photo_id": photo_id, "quality": record.quality}
    raise HTTPException(status_code=404, detail="Photo not found")


@app.post("/people/cluster")
def cluster_people_endpoint(request: PeopleClusterRequest) -> dict:
    try:
        ctx_id = _face_ctx_id(request.ctx_id)
        encoder = InsightFaceEncoder(model_name=request.model_name, ctx_id=ctx_id)
        people = cluster_people(
            service.records,
            encoder,
            model_name=request.model_name,
            eps=request.eps,
            min_samples=request.min_samples,
        )
        save_people_index(people, request.people_path)
        _enrich_quality_with_faces(service, people)
    except (ImportError, RuntimeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return {
        "photo_count": len({face.photo_id for face in people.faces}),
        "face_count": len(people.faces),
        "group_count": len(people.groups),
        "noise_face_count": len(people.noise_face_ids),
        "people_path": request.people_path,
        "ctx_id": ctx_id,
    }


@app.get("/people")
def people(people_path: str = "data/people.json") -> dict:
    return load_people_index(people_path).to_dict()


@app.post("/people/merge")
def merge_people(request: PeopleMergeRequest) -> dict:
    try:
        people_index = load_people_index(request.people_path)
        people_index = apply_feedback(people_index, merges=[request.person_ids])
        save_people_index(people_index, request.people_path)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return people_index.to_dict()


@app.post("/people/remove-photo")
def remove_person_photo(request: PeopleRemovePhotoRequest) -> dict:
    try:
        people_index = load_people_index(request.people_path)
        people_index = apply_feedback(
            people_index,
            removed_photos=[{"person_id": request.person_id, "photo_id": request.photo_id}],
        )
        save_people_index(people_index, request.people_path)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return people_index.to_dict()


@app.post("/people/name")
def name_person(request: PeopleNameRequest) -> dict:
    try:
        people_index = load_people_index(request.people_path)
        people_index = set_person_name(people_index, request.person_id, request.name)
        save_people_index(people_index, request.people_path)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return people_index.to_dict()
